title: Rudi - documentation
description: >
    La documentation de la plateforme Rudi

twitter_username: projetrudi
github_username:  sigrennesmetropole
github_repository: rudi-platform/rudi-documentation
master_branch: main
url: https://rudi-platform.github.io/rudi-documentation
lang: fr
permalink: pretty
year: 2022

i18n:
  en:
    edit: Edit this page
  fr:
    edit: Editer cette page

exclude:
  - .circle/
  - .idea/
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - README.md

# Collection configuration
# Specify a directory to store all our collections in the same place
collections_dir: articles

# Metadata for our collections
collections:
      
  glossaire:
    order: 1
    title: Glossaire
    output: true
    -Généralités: https://github.com/rudi-platform/rudi-documentation/blob/main/articles/_glossaire/general.md
    -Rôles: https://github.com/rudi-platform/rudi-documentation/blob/main/articles/_glossaire/roles.md
    -Utilisateurs et comptes: https://github.com/rudi-platform/rudi-documentation/blob/main/articles/_glossaire/utilisateurs-comptes.md
    -Données de Rudi: https://github.com/rudi-platform/rudi-documentation/blob/main/articles/_glossaire/donnees-rudi.md
    -Concepts de Rudi: https://github.com/rudi-platform/rudi-documentation/blob/main/articles/_glossaire/concepts-rudi.md
    
  espace_personnel_explication:
    order: 2
    title: Comprendre les espaces personnels
    output: true
     
  acces_donnee_ouverte:
    order: 3
    title: Accéder à des données ouvertes
    output: true
  
  acces_donnees_restreintes:
    order: 4
    title: Accéder à des données en accès restreint
    output: true
    
  donnees_personnelles:
    order: 5
    title: Accéder à vos données personnelles
    output: true
    
  authentification:
    order: 6
    title: S'authentifier sur le portail
    output: true
    
  api:
    order: 7
    title: API
    output: true
    
  organisation:
    order: 8
    title: Organisation
    output: true
 
  publication:
    order: 9
    title: Noeud producteur
    output: true

  jeux_de_donnees_geo:
    order: 10
    title: Publier des jeux de données géographiques
    output: true
  
  autres:
    order: 11
    title: Autres
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

sass:
  style: compressed
