version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0

    working_directory: ~/rudi_documentation

    steps:
      - checkout

      - run:
          name: Install Ruby dependencies
          command: bundle install

      - run:
          name: check for deprecations or configuration issues
          command: bundle exec jekyll doctor

      - run:
          name: Build website
          command: bundle exec jekyll build --verbose

      - persist_to_workspace:
          root: .
          paths:
          - _site

  deploy:
    docker:
      - image: cimg/python:3.10.1

    working_directory: ~/rudi_documentation

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Expose user pip-installed binaries on path
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            # Pour mettre à jour la clé suivre : https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-deploy-key
            # Se connecter à https://app.circleci.com en utilisant un compte github 
            # Demander l'accès pour circleci à cette organisation
            # Générer une clé par exemple avec ssh-keygen -t ed25519 -C "rudi-platform/rudi-documentation"
            # Dans la liste des projets de l'organisation sélectionner le projet (rudi-documentation) puis dans
            # Project Settings > SSH Keys > Additionl SSH Keys ajouter le nouvelle clé 
            # S'affiche alors le finger print à utiliser ci-dessous (à mettre ligne2 ci-dessous)
            # Et le MD5 peut-être généré comme suit ssh-keygen -l -E md5 -f id_ed25519 (à mettre ligne1 ci-dessous)
            # Pour finir ajour la clé publique dans rudi-platform/rudi-documentation > Settings (menu code, issues, pull request, ..., settings) > Deploy keys
            - "f3:05:ad:e8:28:80:37:e3:73:5a:6b:d9:12:f8:f0:05"
            - "SHA256:TpurawZETJFOJubDp3G9Hez+DYqXxc277Q/UA5zgtJM"
      - run:
          name: Deploy to GitHub Pages
          command: |
            pip install --user ghp-import
            cp -R .circleci _site/
            git config --global user.name rudi-account-service
            git config --global user.email projet-rudi@open-groupe.com
            ghp-import --cname=doc.rudi.fr -m "Deploy to GitHub pages" --push _site 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Build on any branch except github pages
      - build:
          filters:
            branches:
              ignore: gh-pages
      # Deploy only on master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
